# syntax=docker/dockerfile:1.4
FROM node:22.16-alpine3.21

RUN apk add -f --update --no-cache libc6-compat python3 make g++

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npx prisma generate

ARG START_COMMAND=dev
CMD npm run ${START_COMMAND}
