-- AlterEnum
ALTER TYPE "ExpenseKind" ADD VALUE 'DEPOSIT';
ALTER TYPE "ExpenseKind" ADD VALUE 'WITHDRAWAL';

-- AlterTable
ALTER TABLE "cash_closes" ADD COLUMN "deposits" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "withdrawals" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "bank_opening" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "bank_expected" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "bank_counted" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "bank_variance" INTEGER NOT NULL DEFAULT 0;
