import { createZodDto } from "nestjs-zod";
import { adjustStockSchema } from "../../interfaces/http/validations/adjust-stock.validation";
import { consumeStockSchema } from "../../interfaces/http/validations/consume-stock.validation";
import { createIngredientSchema } from "../../interfaces/http/validations/create-ingredient.validation";
import { fetchBuyListSchema } from "../../interfaces/http/validations/fetch-buy-list.validation";
import { fetchPurchasesSchema } from "../../interfaces/http/validations/fetch-purchases.validation";
import { fetchUsageSchema } from "../../interfaces/http/validations/fetch-usage.validation";
import { fetchQualitySchema } from "../../interfaces/http/validations/fetch-quality.validation";
import { receiveDeliverySchema } from "../../interfaces/http/validations/receive-delivery.validation";
import { submitStockTakeSchema } from "../../interfaces/http/validations/submit-stock-take.validation";
import { setRecipeSchema } from "../../interfaces/http/validations/set-recipe.validation";
import { transferStockSchema } from "../../interfaces/http/validations/transfer-stock.validation";
import { updateIngredientSchema } from "../../interfaces/http/validations/update-ingredient.validation";

export class ConsumeStockDto extends createZodDto(consumeStockSchema) {}
export class CreateIngredientDto extends createZodDto(createIngredientSchema) {}
export class UpdateIngredientDto extends createZodDto(updateIngredientSchema) {}
export class ReceiveDeliveryDto extends createZodDto(receiveDeliverySchema) {}
export class AdjustStockDto extends createZodDto(adjustStockSchema) {}
export class SetRecipeDto extends createZodDto(setRecipeSchema) {}
export class FetchQualityDto extends createZodDto(fetchQualitySchema) {}
export class FetchPurchasesDto extends createZodDto(fetchPurchasesSchema) {}
export class FetchUsageDto extends createZodDto(fetchUsageSchema) {}
export class FetchBuyListDto extends createZodDto(fetchBuyListSchema) {}
export class SubmitStockTakeDto extends createZodDto(submitStockTakeSchema) {}
export class TransferStockDto extends createZodDto(transferStockSchema) {}
